AWSTemplateFormatVersion: 2010-09-09
Description: Template for Local LLM environment
Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-013a28d7c2ea10269
      InstanceType: !Ref InstanceTypeParameter
      KeyName: !Ref SSHKeyParameter
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp3
            Iops: 3000
            DeleteOnTermination: true
            VolumeSize: 60
    DeletionPolicy: Retain
Parameters:
  SSHKeyParameter:
    Type: AWS::EC2::KeyPair::KeyName
    Description: name of the key pair to ssh into the instance
  InstanceTypeParameter:
    Type: String
    Default: t3.xlarge
    AllowedValues:
      - t2.xlarge
      - t2.2xlarge
      - t3.xlarge
      - t3.2xlarge
      - t3a.xlarge
      - t3a.2xlarge
      - m5.xlarge
      - m5.2xlarge
    Description: Select the instance type. only the memory 16GiB+ is capable for LLM.